gctsDeploy(
  script: this,
  host: 'https://hcluks4hana.hcldigilabs.com:8001/',
  client: '200',
  abapCredentialsId: 'ABAPUserPasswordCredentialsId',
  repository: 'HCL-Githup',
  remoteRepositoryURL: "https://github.com/abhilashhaa/HCL_Githup.git",
  role: 'SOURCE',
  vSID: 'FEF',
  branch: 'master',
  commit: 'commit',
  scope: 'scope',
  rollback: false,
  configuration: [dummyConfig: 'dummyval']
   
