

 stage('DeployCommit')         
             steps:  
                gctsDeploy:
                 script: this,
                host: 'https://hclutl1909.hcldigilabs.com:8001/',
                client: '000',
                abapCredentialsId: 'ABAPUserPasswordCredentialsId',
                repository: 'HCL-Githup',
                remoteRepositoryURL: "https://github.com/abhilashhaa/HCL_Githup.git",
                role: 'TARGET',
                vSID: 'FEF',
                
               
                
               
   
